#ifndef CONSTANTS_H
#define CONSTANTS_H

#define CELL_SIZE 50
#define MAP_WIDTH 30
#define MAP_HEIGHT 20

#define HERO_START_HP 100
#define HERO_MAX_HP 100
#define HERO_ATK 10
#define HERO_ACC 50
#define HERO_AGL 20
#define HERO_RES 10
#define HERO_CRIT 5
#define HERO_INF 0

#define NORMAL_MONSTER_HP 20
#define NORMAL_MONSTER_MAX_HP 20
#define NORMAL_MONSTER_ATK 10

#define INFECTED_MONSTER_HP 30
#define INFECTED_MONSTER_MAX_HP 30
#define INFECTED_MONSTER_ATK 15
#define INFECTED_MONSTER_INFECTION_POWER 20

#define HEAL_POTION_AMOUNT 20
#define ANTIDOTE_AMOUNT 30
#define ARMOR_DEF 5
#define WEAPON_DAMAGE 15

#define CAMERA_SPEED 0.1f

#endif
